name: searching_list_with_json
description: A new Flutter project.

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #http service
  http: ^0.13.3

  #emails send
  url_launcher: ^6.0.9

  #animation lottie file
  lottie: ^1.1.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:

  uses-material-design: true

  assets:
    - assets/
